name: dictionary
description: "Aplikasi Kamus Terjemahan Bahasa Daerah Kailolo - Indonesia."

publish_to: "Link"

version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  carousel_slider: ^4.2.1
  change_app_package_name: ^1.5.0
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  font_awesome_flutter: ^10.8.0
  http: ^1.2.1
  intl: ^0.19.0
  json_annotation: ^4.8.1
  path_provider: ^2.1.3
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
